# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: monitoring CI

on:
  push:
    paths:
    - 'monitoring/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # node-version: [12.x, 14.x, 16.x]
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: monitoring/package-lock.json
    - run: npm ci
      working-directory: monitoring
    - run: npm run build --if-present
      working-directory: monitoring
    # - run: npm test # Omitting Tests as this service does not have any currently. 
  push_image:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v2
        name: Use Node.js ${{ matrix.node-version }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build, tag, and push image to DockerHub
        env:
          REGISTRY: bilal690
          REPOSITORY: banking-monitoring
          IMAGE_TAG: 0.1.develop
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -f ./monitoring/Dockerfile ./monitoring
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG