# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: rest-services CI

on:
  push:
    paths:
    - 'rest-services/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # node-version: [12.x, 14.x, 16.x]
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: rest-services/package-lock.json
    - run: npm ci
      working-directory: rest-services
    - run: npm run build --if-present
      working-directory: rest-services
    # - run: npm test # Omitting Tests as this service does not have any currently. 
  push_image:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v2
        name: Use Node.js ${{ matrix.node-version }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build, tag, and push image to DockerHub
        env:
          REGISTRY: bilal690
          ACCOUNTS_REPOSITORY: banking-accounts
          CONTACTS_REPOSITORY: banking-contacts
          CUSTOMER_REPOSITORY: banking-customer
          TRANSACTIONS_REPOSITORY: banking-transactions
          IMAGE_TAG: 0.1.develop
        run: |
          docker build -t $REGISTRY/$ACCOUNTS_REPOSITORY:$IMAGE_TAG -f ./rest-services/Dockerfile --build-arg REST_SERVICE=instances/accounts.js ./rest-services
          docker build -t $REGISTRY/$CONTACTS_REPOSITORY:$IMAGE_TAG -f ./rest-services/Dockerfile --build-arg REST_SERVICE=instances/contacts.js ./rest-services
          docker build -t $REGISTRY/$CUSTOMER_REPOSITORY:$IMAGE_TAG -f ./rest-services/Dockerfile --build-arg REST_SERVICE=instances/customer.js ./rest-services
          docker build -t $REGISTRY/$TRANSACTIONS_REPOSITORY:$IMAGE_TAG -f ./rest-services/Dockerfile --build-arg REST_SERVICE=instances/transactions.js ./rest-services

          docker push $REGISTRY/$ACCOUNTS_REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$CONTACTS_REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$CUSTOMER_REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$TRANSACTIONS_REPOSITORY:$IMAGE_TAG